import java.security.PublicKey;
import java.util.List;

import javax.crypto.SecretKey;

public interface KeyManager extends KeyManagerKernel {
    // Secondary Methods

    /**
     * Generates a new key and replaces all of the keys in KEYSTORE
     *
     * @requires Each call to keyRetreival produces metadata with one key name and valid usage at index [0]
     * 
     * @ensures KEYSTORE contains a new key at keyName and the previous key is
     *          archived or destroyed.
     */
    void keyRotation();

    /**
     * Exports a log of all keys and their details
     *
     * @param filePath
     *            The path of the file you want to contain the log
     * @ensures
     *            The file contains all the keys and there associated data if the file path exists and throws
     *            an error if it doesn't. No changes are made to the KEYSTORE
     */
    void exportKeyLog(String filePath);

    /**
     * Destroys all keys that have expired.
     *
     * @requires The keys have a creation date metaData stored at index [1] of the List
     * 
     * @ensures All expired keys are removed from the KEYSTORE.
     */
    void cleanupExpiredKeys();

    /**
     * Searches the KEYSTORE and returns all key names that have an "access"
     * metadata entry containing the specified access level.
     *
     * @param access
     *            The access level to match (access key)
     *
     * @return A list of key names in KEYSTORE whose metadata contains the
     *         access value
     *
     * @requires KEYSTORE is initialized and contains metadata entries for keys at index [2]
     *
     * @ensures a list of keys matching your associated access level is given and
     *          no modifications are made to the KEYSTORE
     */
    List<String> findKeysByAccess(SecretKey access);

    /**
     * Verifies the digital signature of each key in the KEYSTORE using the
     * provided public key. Each key's metadata is expected to contain a digital
     * signature (Base64-encoded) at index 3 of its associated list, which was
     * originally generated by signing the key name using the corresponding
     * private key. This method verifies that signature against the provided
     * public key.
     *
     * @param publicKey
     *            The public key corresponding to the private key that signed
     *            the key names.
     *
     * @return {true} if all the key's signature are valid (i.e.,
     *         correctly signed with the matching private key), {false}
     *         otherwise.
     *
     * @requires KEYSTORE is initialized and contains at least one key. -
     *           Metadata for each key includes a Base64-encoded digital
     *           signature at index 3 of its value list. - Each key name was
     *           originally signed using the corresponding private key.
     *
     * @ensures No modifications are made to the KEYSTORE. Returns true if
     *          any signature is successfully verified using the given public
     *          key.
     */
    boolean verifyKeySignatures(PublicKey publicKey);
}
